# Generated by Django 4.0.1 on 2022-01-26 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=200)),
                ('birthday', models.DateField()),
                ('email', models.EmailField(max_length=100)),
                ('phone_number', models.CharField(max_length=30)),
                ('recommender', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
