# Generated by Django 4.0.1 on 2022-02-08 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='point',
            field=models.DecimalField(decimal_places=0, default='0', max_digits=30),
        ),
    ]
