# Generated by Django 4.0.1 on 2022-01-26 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='recommender',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
