# Generated by Django 4.0.1 on 2022-02-03 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_alter_colorthumbnail_product_color'),
        ('users', '0001_initial'),
    ]

    # operations = [
    #     migrations.CreateModel(
    #         name='Cart',
    #         fields=[
    #             ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
    #             ('created_at', models.DateTimeField(auto_now_add=True)),
    #             ('updated_at', models.DateTimeField(auto_now=True)),
    #             ('quantity', models.IntegerField()),
    #             ('product_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productoption')),
    #             ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
    #         ],
    #         options={
    #             'db_table': 'carts',
    #         },
    #     ),
    # ]
