# Generated by Django 4.0.1 on 2022-02-03 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colorthumbnail',
            name='product_color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_color', to='products.productcolor'),
        ),
    ]
