# Generated by Django 4.0.1 on 2022-02-05 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_colorthumbnail_product_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colorthumbnail',
            name='product_color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colors_thumbnails', to='products.productcolor'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product_color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products_images', to='products.productcolor'),
        ),
    ]
