# Generated by Django 4.0.1 on 2022-02-07 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_productcolor_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productcolor',
            old_name='like',
            new_name='like_cnt',
        ),
    ]
